services:
  server:
    build: .
    image: shareit-server:0.2
    container_name: shareit-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=123456
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=123456
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10