TRUNCATE TABLE shareit.bookings RESTART IDENTITY CASCADE;
TRUNCATE TABLE shareit.items RESTART IDENTITY CASCADE;
TRUNCATE TABLE shareit.requests RESTART IDENTITY CASCADE;
TRUNCATE TABLE shareit.users RESTART IDENTITY CASCADE;
TRUNCATE TABLE shareit.comments RESTART IDENTITY CASCADE;